# Generated by Django 4.2.2 on 2023-06-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartitems',
            fields=[
                ('cid', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
                ('price', models.IntegerField(max_length=1000)),
                ('totprice', models.IntegerField(max_length=1000)),
                ('tag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='foods',
            fields=[
                ('fid', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(max_length=1000)),
                ('tag', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=10000)),
            ],
        ),
    ]
