# Generated by Django 4.2.2 on 2023-06-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='totprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='fid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.IntegerField(),
        ),
    ]
