# Generated by Django 4.2.2 on 2023-06-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0002_alter_cartitems_cid_alter_cartitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='pic',
            field=models.CharField(default='x', max_length=1000),
        ),
    ]
