# Generated by Django 4.2.2 on 2023-06-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0004_usersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='userid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='foodapi.usersignup'),
            preserve_default=False,
        ),
    ]
