# Generated by Django 4.2.2 on 2023-06-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0005_cartitems_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('revdesc', models.CharField(max_length=10000)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapi.foods')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapi.usersignup')),
            ],
        ),
    ]
