# Generated by Django 4.2.2 on 2023-06-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0007_alter_reviews_rate_alter_reviews_revdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='username',
            new_name='userid',
        ),
    ]
